AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bahn-lambda

  Sample SAM Template for bahn-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Metadata:
  AWS::ServerlessRepo::Application:
    Name: bahn-api-bot
    Description: "Bot that calls the Bahn API"
    Author: John Sorial
    HomePageUrl: https://github.com/user1/my-app-project
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/user1/my-app-project

Resources:
  BahnAlexaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist
      Handler: src/index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          NODE_OPTIONS: --enable-source-maps

