name: Deploy MyOPNV Alexa

on: [ workflow_dispatch,push ]


jobs:
  deploy-meinOPNV-skill:
    name: "Deploy OPNV skill"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::647890429578:role/bahn-github
          aws-region: eu-west-1

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Setup Dependencies
        run: |
          yarn install --immutable
          npm install -g nx@latest
      - name: Generate Prisma Client
        working-directory: ./apps/alexa-skill
        run: |
          yarn prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Deploy Lambda
        working-directory: ./apps/alexa-skill
        run: |
          yarn deploy
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
